services:
  sunnyportal-scraper:
    image: mcr.microsoft.com/playwright:v1.51.1-noble
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    working_dir: /app
    volumes:
      - .:/app:cached
    command: sh -c "npm ci && npx playwright install && npm start"