version: '3.8'

services:
  sunnyportal-scraper:
    image: mcr.microsoft.com/playwright:focal
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npx playwright install && npm start"
