version: '3.8'

services:
  sunnyportal-scraper:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
