version: '3.8'

services:
  sunnyportal-scraper:
    image: mcr.microsoft.com/playwright:v1.51.1-noble
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "if [ ! -d 'node_modules' ]; then npm install; fi && npx playwright install && npm start"
